- name: install docker in all machine
  hosts: servers
  become: yes

  roles:
    - role: ../roles/docker
      docker_users:
        - ubuntu
        - ec2-user
      docker_service_enabled: true    
