# Ansible Inventory — Auto-generated by Terraform
# Teaching inventory: run this FROM the control node.
# The control node manages itself locally and reaches workers by PRIVATE IP.

[all:vars]
ansible_python_interpreter=/usr/bin/python3

[control]
%{ for name, inst in control ~}
${name} ansible_connection=local ansible_user=${inst.user}
%{ endfor ~}

[ubuntu_workers]
%{ for name, inst in ubuntu_workers ~}
${name} ansible_host=${inst.private_ip} ansible_user=${inst.user}
%{ endfor ~}

[redhat]
%{ for name, inst in redhat ~}
${name} ansible_host=${inst.private_ip} ansible_user=${inst.user}
%{ endfor ~}

[amazon]
%{ for name, inst in amazon ~}
${name} ansible_host=${inst.private_ip} ansible_user=${inst.user}
%{ endfor ~}

[workers:children]
ubuntu_workers